# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            WPF
tagline:          'A Test Site'
description:      'A test site based on <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, a theme that pairs a prominent sidebar with uncomplicated content. Theme created by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /wpfranks.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
